Self/mydevorg/Unpackaged/Config/objects/Avon_Genealogy__c.object
<CustomObject>
    <fields>
        <fullName>LFT_ND_ID__c</fullName>
        <label>Left Node Id</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Children__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Children</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RGT_ND_ID__c</fullName>
        <label>Right Node Id</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Avon Genealogy</label>
    <nameField>
        <label>Avon Genealogy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genealogy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Self/mydevorg/Unpackaged/Code/classes/AvonPopulateRootLftRgt.cls
global with sharing class AvonPopulateRootLftRgt implements 
    Database.Batchable<sObject>{
 
     //we want the list to be reset after every batch. This list is used only during the duration of the single batch execution
      //stores the list of genealogy instances to be updated
   static List <Avon_Genealogy__c> genealogyListToBeUpdated=new List<Avon_Genealogy__c>();
   global final String Query;
   
   global AvonPopulateRootLftRgt(String q){
   	  Query=q;
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
   	  return Database.getQueryLocator(query);
   }
   
   global void execute(
                Database.BatchableContext BC, 
                List<sObject> scope){ 
         
         for(sObject sObj:scope){
         	Avon_Genealogy__c genInstance=(Avon_Genealogy__c)sObj;
         	genInstance.LFT_ND_ID__c=1;
         	genInstance.RGT_ND_ID__c=(genInstance.Number_of_Children__c + 1)*2;
         	genealogyListToBeUpdated.add(genInstance);
         }
         
         //execute the update operation on the genealogy objects for the current batch
      try{
      	update genealogyListToBeUpdated;
      }
      catch(Exception e){
      	//TODO: Handle appropriate exception and report error to the end user.
      }
                
    }

global void finish(Database.BatchableContext BC){
   }
}