Self/mydevorg/Unpackaged/Config/objects/Establishment__c.object
<CustomObject>
    <description>Establishments for Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account related to the Establishment</description>
        <inlineHelpText>Link the Account to the Establishment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Establishments</relationshipLabel>
        <relationshipName>Establishments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City_Name__c</fullName>
        <description>Name of the city where the establishment is located. Generally in the local language</description>
        <inlineHelpText>Name of the city where the establishment is located. Generally in the local language</inlineHelpText>
        <label>City Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Legacy System Identifier</description>
        <externalId>true</externalId>
        <inlineHelpText>Legacy System Identifier</inlineHelpText>
        <label>Source System ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Establishment</label>
    <nameField>
        <label>Legal Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Establishments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Self/mydevorg/Unpackaged/Config/objects/Visibility__c.object
<CustomObject>
    <description>The custom object that controls the visibility of accounts and establishments</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The account that need to be accessed by the user mentioned.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visibility</relationshipLabel>
        <relationshipName>Visibility</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Establishment__c</fullName>
        <label>Establishment</label>
        <referenceTo>Establishment__c</referenceTo>
        <relationshipLabel>Visibility</relationshipLabel>
        <relationshipName>Visibility</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visibility</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visibility</label>
    <nameField>
        <label>Establishment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visibility</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Self/mydevorg/Unpackaged/Code/classes/EsTabsDisplay.cls
/**
 * Class to display the establishments based on visibility settings
 *
 */

public with sharing class EsTabsDisplay {

  Account accountInstance;
  
  List<String> userIds;
  
  
  public EsTabsDisplay(Apexpages.standardcontroller accountController){
  	  accountInstance=(Account)accountController.getRecord();
  	  userIds=new List<String>();
  	  if(accountInstance!=null){
	  	  for(AccountTeamMember teamMemberInstance:[select Id, AccountId, UserId from AccountTeamMember where AccountId=:accountInstance.id]){
	  	  	  userIds.add(teamMemberInstance.UserId);
	  	  }
	  	  userIds.add(accountInstance.OwnerId);
	  	  //userIds.add(Userinfo.getUserId());
  	  }
  }

  public List<Visibility__c> getEstablishments(){
  	
  	System.debug('====in getEstablishments Method====' + userIds);
  	
  	Map<Id,Visibility__c> retVisibilityMap=new Map<Id,Visibility__c>();
  	
  	for(Visibility__c visibilityInstance :[select Id
  	                                            , Establishment__c
  	                                            , Establishment__r.Name
  	                                            , Establishment__r.City_Name__c
  	                                            , Establishment__r.Account__c
  	                                            , Establishment__r.Source_System_ID__c
  	                                           , User__c 
  	                                       from Visibility__c
  	                                       where User__c =:userIds
  	                                       and Account__c=:accountInstance.id]){
  	                                                          	
  	          retVisibilityMap.put(visibilityInstance.Establishment__c,visibilityInstance);
  	 }
  	  
  	  /*hasEstabs=(retVisibilityMap.size()>0);
  	  
  	  System.debug('====hasEstabs====' + hasEstabs);
  	  
  	  if(retVisibilityMap.size()>0){
  	  	ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, 'No eligible establishments found for ' + accountInstance.name));
  	  }*/
  	  
  	  return   retVisibilityMap.values();                                                      	
  }
  
}